### ISSUE TITLE
Pause and restart

### ISSUE THREAD

**Issue by JulienPascal** [floswald/MomentOpt.jl#17]
Hi, 

Thank you for the awesome work. 
Is there any way to "pause" the estimation and to restart from the same point?

Cheers,
Julien

**Comment by floswald** [comment]
no, but that would be a good feature. you can save and load an `AlgoBGP` object from disk already. so the pieces are all there, just need to connect them somehow. sounds like a pull request to me? :-)

**Comment by JulienPascal** [comment]
Can we convert this "issue" into a milestone?
For an unknown reason, I can't just follow this tutorial: https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests
At step 4, the option "New Milestone" is not there.
![image](https://user-images.githubusercontent.com/15772983/36474673-7fc33d22-16f8-11e8-8632-525a1ebfd5d2.png)

**Comment by floswald** [comment]
why do you want to do this?

**Comment by JulienPascal** [comment]
What I mentioned is not an issue per se. It's more of a new feature for next versions. Maybe milestones are a convenient device for listing such extensions? (https://www.youtube.com/watch?v=ukYSRu4k0gs)

**Comment by floswald** [comment]
i see. that's fine as an issue I think. :-)

**Comment by JulienPascal** [comment]
Since JLD2 supports saving functions, it seems to be the way to go for me. 
If you agree, I can prepare a PR. 
I also see that in order to save every x iterations, the user needs to include "save_frequency" and "filename" in when setting up the opts dictionary. Is that right? If yes, it should probably appear in the README or docs. 
Cheers,
Julien

**Comment by JulienPascal** [comment]
It appears to be more complicated than initially planned. Simply saving the entire `MAlgoBGP` does not work, as JLD2 does not seem to fully comprehend the structure of this object. When loading the same object, some information is lost regarding the chains.

I have made some experiments and it seems that it is necessary to save each chain individually. But then it would imply a large number of files when working with several chains. 

Any thought on this matter?

**Comment by floswald** [comment]
Ok I feared that. We have (had) code to write a chain to an hdf5 file. We
don’t need that anymore, since writing a dataframe directly now works. So
what do we need to store for a restart?

1) the opts dict
2) the relevant dataframe(s?)
3) something indicating the type of algo (malgobgp eg)

From that it must be possible to recreate an malgobgp and resume estimation.

Thoughts?

**Comment by JulienPascal** [comment]
I am weighing the pros and the cons of using a dataframe for chains.
On the one hand, it would avoid the issue of having several files when working with several chains, which is great. But on the other hand, the chains attached to a MAlgoBGP would have to be re-created using the dataframe. So that means creating a new functions to do that. I don't know how much time it would take. 

Regarding what to be saved, MAlgoBGP contains 6 fields:
*  m
* opts
* i
* chains
* anim
* dist_func

My gut feeling is that only `chains` deserved a special treatment (and maybe  `anim`,  but I am not even sure that animation are still currently supported). So it would be perfectly fine to store the "easy ones" in a single JLD2 file:
```julia
@JLD2.save "filename" MAlgoBGP.m MAlgoBGP.opts MAlgoBGP.i MAlgoBGP.dist_func
```

Then something would have to be done for  `MAlgoBGP.chains`. For the moment I have a patch that creates one file for each chain. Yet, if you think that using a dataframe is the way to go, I will have a look and see to what extent this is feasible.

**Comment by JulienPascal** [comment]
I have news on this side. The issue was not related to JLD2, but it was a subtle one about the type `BGPChain`:
```julia
type BGPChain <: AbstractChain
    evals     :: Array{Eval}
    best_id   :: Vector{Int}   # index of best eval.value so far
    best_val  :: Vector{Float64}   # best eval.value so far
    curr_val  :: Vector{Float64}   # current value
    probs_acc :: Vector{Float64}    # vector of probabilities with which to accept
    #mprob     :: MProb
    id        :: Int64
    iter      :: Int64
    accepted  :: Array{Bool}
    accept_rate :: Float64
    acc_tuner :: Float64
    exchanged :: Array{Int}
    m         :: MProb
    sigma     :: PDiagMat{Float64}
    sigma_update_steps :: Int64   # update sampling vars every sigma_update_steps iterations
    sigma_adjust_by :: Float64   # adjust sampling vars by sigma_adjust_by percent up or down
    smpl_iters :: Int64   # max number of trials to get a new parameter from MvNormal that lies within support
    maxdist  :: Float64 
```
The `mprob` that I have commented out should not be there. There is already `m`. Given that `mprob` was never assigned any value, trying to load a BGPChain with JLD2 would return an error ("undefined reference"). 

Without this extra `mprob`, saving and loading the entire `MAlgoBGP` does work like a charm.

**Comment by JulienPascal** [comment]
This is no longer an issue, since the PR has been merged. Thanks.
