### ISSUE TITLE
Minor issue with field best_id in BGPChain

### ISSUE THREAD

**Issue by edoardociscato** [floswald/MomentOpt.jl#19]
https://github.com/floswald/MomentOpt.jl/blob/0c90a769d42aad3c29d1f5aecf5a49cd1e63f406/src/mopt/AlgoBGP.jl#L179-L199

As you can see in line 197 `c.best_id[c.iter]` is set to be equal to `c.iter` even when the new value at iteration `c.iter` is not the best value in the chain. Once the algorithm is done, I get that `c.best_id` is simply `1:opts["maxiter"]`. I guess `c.best_id[c.iter]` should probably be set to `c.best_id[c.iter-1]` (exactly in the same way as `c.best_val[c.iter]` in line 196).

Note that I am almost sure that this does not affect the functioning of the BGP algorithm, nor of any other function in this package. It only makes it a bit more complicated to retrieve the iteration at which the lowest value has been found.

It should be any easy fix, just wanted to check with you that this is indeed a minor issue.

**Comment by floswald** [comment]
yeah i'm not sure whether the algorithm is actually using this - at least I don't remember its purpose now! but your proposition sounds correct, i think that's what `best_id` should capture. even tough the name is not great, as i immediately thought of *chain* `id`. in stead it's the index of the best value on that chain. so: i would change the name to `best_idx` and make the change you proposed. PR welcome! thanks!
