### ISSUE TITLE
Re-scaling parameters to unit range

### ISSUE THREAD

**Issue by JulienPascal** [floswald/MomentOpt.jl#38]
Hi,

It seems like it's harder for the algorithm to find the minimum when working with parameters of different order of magnitude (let's say 1 versus 0.01, as your examples in the README).

Maybe an easy fix would be to automatically re-scale each parameter to `[0,1]` (or `[-1,1]`)?

Of course, when calling the objective function, we need to make sure that we transform back `[0,1]^n` to
its original value (`n` being the number of parameters to estimate). But the algorithm itself would be working only with `[0,1]^n`.

Does it make sense? 

If yes, I can implement this on a new branch and make a PR.

Cheers

**Comment by floswald** [comment]
Yes that makes sense! I have mostly been concerned about moments living on
different scales in my applications, and there a different objective
function helps. But you are right: the bgp proposal fails if the space of
parameters is not regular. So yes we should internally have all  p in the
unit interval, where zero means lower bound and one upper bound. PR more
than welcome!

**Comment by JulienPascal** [comment]
Ok, great.

Before creating a new branch, should I be concerned about tests failing on the master branch?

Regarding moments of different scales, setting weight = value (working with percentage differences) is 
not enough ?

**Comment by floswald** [comment]
yes, adjusting the weight in this way is kind of what i do.  tests were not
up to date! now ok.

**Comment by floswald** [comment]
@JulienPascal did you ever start with this? I'm asking because I would start myself with developing this now if you hadn't. cheers

**Comment by JulienPascal** [comment]
Hi @floswald . No I haven't started yet.

**Comment by floswald** [comment]
#39 does that. have a look!
